# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'expense_tracker.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 480)
        MainWindow.setStyleSheet("\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427 rgba(41, 61, 132, 235), stop:0.98 rgba(155, 79, 165, 255), stop:1 rgba(155, 79, 165, 255));\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.balance_frame = QtWidgets.QFrame(self.centralwidget)
        self.balance_frame.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"boreder: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;")
        self.balance_frame.setObjectName("balance_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.balance_frame)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_current_balance = QtWidgets.QLabel(self.balance_frame)
        self.label_current_balance.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 20pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_current_balance.setObjectName("label_current_balance")
        self.verticalLayout.addWidget(self.label_current_balance)
        self.label_balance = QtWidgets.QLabel(self.balance_frame)
        self.label_balance.setStyleSheet("color: white;\n"
"font-size: 25pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: 600;\n"
"margin-bottom: 7px;\n"
"")
        self.label_balance.setObjectName("label_balance")
        self.verticalLayout.addWidget(self.label_balance)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon_up_arrow = QtWidgets.QLabel(self.balance_frame)
        self.icon_up_arrow.setMaximumSize(QtCore.QSize(24, 16777215))
        self.icon_up_arrow.setStyleSheet("background-color: none;\n"
"border: none;\n"
"pading-top: 10px;")
        self.icon_up_arrow.setText("")
        self.icon_up_arrow.setPixmap(QtGui.QPixmap("icons/call_made_white_24dp.svg"))
        self.icon_up_arrow.setObjectName("icon_up_arrow")
        self.horizontalLayout.addWidget(self.icon_up_arrow)
        self.label_income = QtWidgets.QLabel(self.balance_frame)
        self.label_income.setStyleSheet("color: white;\n"
"font-size: 16pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bold;\n"
"pading-top: 10px;")
        self.label_income.setObjectName("label_income")
        self.horizontalLayout.addWidget(self.label_income)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.income_balance = QtWidgets.QLabel(self.balance_frame)
        self.income_balance.setStyleSheet("color: white;\n"
"font-size: 18pt;\n"
"background-color: none;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.income_balance.setObjectName("income_balance")
        self.verticalLayout.addWidget(self.income_balance)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon_down_arrow = QtWidgets.QLabel(self.balance_frame)
        self.icon_down_arrow.setMaximumSize(QtCore.QSize(24, 16777215))
        self.icon_down_arrow.setStyleSheet("background-color: none;\n"
"border: none;\n"
"pading-top: 10px;")
        self.icon_down_arrow.setText("")
        self.icon_down_arrow.setPixmap(QtGui.QPixmap("icons/call_received_white_24dp.svg"))
        self.icon_down_arrow.setObjectName("icon_down_arrow")
        self.horizontalLayout_2.addWidget(self.icon_down_arrow)
        self.label_outcome = QtWidgets.QLabel(self.balance_frame)
        self.label_outcome.setStyleSheet("color: white;\n"
"font-size: 16pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bold;\n"
"pading-top: 10px;")
        self.label_outcome.setObjectName("label_outcome")
        self.horizontalLayout_2.addWidget(self.label_outcome)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.outcome_balance = QtWidgets.QLabel(self.balance_frame)
        self.outcome_balance.setStyleSheet("color: white;\n"
"font-size: 18pt;\n"
"background-color: none;\n"
"border: none;\n"
"margin-top: 1px;")
        self.outcome_balance.setObjectName("outcome_balance")
        self.verticalLayout.addWidget(self.outcome_balance)
        self.horizontalLayout_7.addWidget(self.balance_frame)
        self.categories_frame = QtWidgets.QFrame(self.centralwidget)
        self.categories_frame.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"boreder: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;")
        self.categories_frame.setObjectName("categories_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.categories_frame)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_expense_tracker = QtWidgets.QLabel(self.categories_frame)
        self.label_expense_tracker.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 20pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_expense_tracker.setObjectName("label_expense_tracker")
        self.verticalLayout_2.addWidget(self.label_expense_tracker)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.icon_groceries = QtWidgets.QLabel(self.categories_frame)
        self.icon_groceries.setMaximumSize(QtCore.QSize(24, 16777215))
        self.icon_groceries.setStyleSheet("background-color: none;\n"
"border: none;")
        self.icon_groceries.setText("")
        self.icon_groceries.setPixmap(QtGui.QPixmap("icons/shopping_cart_white_24dp.svg"))
        self.icon_groceries.setObjectName("icon_groceries")
        self.horizontalLayout_6.addWidget(self.icon_groceries)
        self.label_groceries = QtWidgets.QLabel(self.categories_frame)
        self.label_groceries.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: white;\n"
"font-size: 14pt;\n"
"font-weight: bold;")
        self.label_groceries.setObjectName("label_groceries")
        self.horizontalLayout_6.addWidget(self.label_groceries)
        self.balance_groceries = QtWidgets.QLabel(self.categories_frame)
        self.balance_groceries.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: white;\n"
"font-size: 16pt;\n"
"")
        self.balance_groceries.setObjectName("balance_groceries")
        self.horizontalLayout_6.addWidget(self.balance_groceries)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.icon_entertair = QtWidgets.QLabel(self.categories_frame)
        self.icon_entertair.setMaximumSize(QtCore.QSize(24, 16777215))
        self.icon_entertair.setStyleSheet("background-color: none;\n"
"border: none;")
        self.icon_entertair.setText("")
        self.icon_entertair.setPixmap(QtGui.QPixmap("icons/sports_esports_white_24dp.svg"))
        self.icon_entertair.setObjectName("icon_entertair")
        self.horizontalLayout_5.addWidget(self.icon_entertair)
        self.label_entertair = QtWidgets.QLabel(self.categories_frame)
        self.label_entertair.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: white;\n"
"font-size: 14pt;\n"
"font-weight: bold;")
        self.label_entertair.setObjectName("label_entertair")
        self.horizontalLayout_5.addWidget(self.label_entertair)
        self.balance_entertair = QtWidgets.QLabel(self.categories_frame)
        self.balance_entertair.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: white;\n"
"font-size: 16pt;\n"
"")
        self.balance_entertair.setObjectName("balance_entertair")
        self.horizontalLayout_5.addWidget(self.balance_entertair)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.icon_auto = QtWidgets.QLabel(self.categories_frame)
        self.icon_auto.setMaximumSize(QtCore.QSize(24, 16777215))
        self.icon_auto.setStyleSheet("background-color: none;\n"
"border: none;")
        self.icon_auto.setText("")
        self.icon_auto.setPixmap(QtGui.QPixmap("icons/directions_car_white_24dp.svg"))
        self.icon_auto.setObjectName("icon_auto")
        self.horizontalLayout_4.addWidget(self.icon_auto)
        self.label_auto = QtWidgets.QLabel(self.categories_frame)
        self.label_auto.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: white;\n"
"font-size: 14pt;\n"
"font-weight: bold;")
        self.label_auto.setObjectName("label_auto")
        self.horizontalLayout_4.addWidget(self.label_auto)
        self.balance_auto = QtWidgets.QLabel(self.categories_frame)
        self.balance_auto.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: white;\n"
"font-size: 16pt;\n"
"")
        self.balance_auto.setObjectName("balance_auto")
        self.horizontalLayout_4.addWidget(self.balance_auto)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.icon_other = QtWidgets.QLabel(self.categories_frame)
        self.icon_other.setMaximumSize(QtCore.QSize(24, 16777215))
        self.icon_other.setStyleSheet("background-color: none;\n"
"border: none;")
        self.icon_other.setText("")
        self.icon_other.setPixmap(QtGui.QPixmap("icons/web_stories_white_24dp.svg"))
        self.icon_other.setObjectName("icon_other")
        self.horizontalLayout_3.addWidget(self.icon_other)
        self.label_other = QtWidgets.QLabel(self.categories_frame)
        self.label_other.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: white;\n"
"font-size: 14pt;\n"
"font-weight: bold;")
        self.label_other.setObjectName("label_other")
        self.horizontalLayout_3.addWidget(self.label_other)
        self.balance_other = QtWidgets.QLabel(self.categories_frame)
        self.balance_other.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: white;\n"
"font-size: 16pt;\n"
"")
        self.balance_other.setObjectName("balance_other")
        self.horizontalLayout_3.addWidget(self.balance_other)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7.addWidget(self.categories_frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.action_with_transactions = QtWidgets.QHBoxLayout()
        self.action_with_transactions.setObjectName("action_with_transactions")
        self.btn_new_transaction = QtWidgets.QPushButton(self.centralwidget)
        self.btn_new_transaction.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 255, 255, 30);\n"
"color: white;\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"width: 230px;\n"
"height: 50px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/add_box_white_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new_transaction.setIcon(icon)
        self.btn_new_transaction.setIconSize(QtCore.QSize(24, 24))
        self.btn_new_transaction.setObjectName("btn_new_transaction")
        self.action_with_transactions.addWidget(self.btn_new_transaction)
        self.btn_edit_transaction = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit_transaction.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 255, 255, 30);\n"
"color: white;\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"width: 230px;\n"
"height: 50px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/edit_white_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit_transaction.setIcon(icon1)
        self.btn_edit_transaction.setIconSize(QtCore.QSize(24, 24))
        self.btn_edit_transaction.setObjectName("btn_edit_transaction")
        self.action_with_transactions.addWidget(self.btn_edit_transaction)
        self.btn_delete_transaction = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete_transaction.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 255, 255, 30);\n"
"color: white;\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"width: 230px;\n"
"height: 50px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/delete_white_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete_transaction.setIcon(icon2)
        self.btn_delete_transaction.setIconSize(QtCore.QSize(24, 24))
        self.btn_delete_transaction.setObjectName("btn_delete_transaction")
        self.action_with_transactions.addWidget(self.btn_delete_transaction)
        self.verticalLayout_3.addLayout(self.action_with_transactions)
        self.table_transactions = QtWidgets.QTableView(self.centralwidget)
        self.table_transactions.setStyleSheet("QTableView {\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid  rgba(255, 255, 255, 40);\n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"}\n"
"\n"
"QTableView:section {\n"
"background-color: rgba(53, 53, 53);\n"
"color: white;\n"
"border: none;\n"
"height: 50px;\n"
"font-size: 14pt;\n"
"}\n"
"\n"
"QTableView:item {\n"
"border-style: none;\n"
"border-bottom: rgba(255, 255, 255, 50);\n"
"}\n"
"\n"
"QTableView:item:selected {\n"
"color:  rgba(255, 255, 255);\n"
"border: none;\n"
"background-color:  rgba(255, 255, 255, 50);\n"
"}")
        self.table_transactions.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_transactions.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_transactions.setShowGrid(False)
        self.table_transactions.setObjectName("table_transactions")
        self.table_transactions.horizontalHeader().setDefaultSectionSize(135)
        self.verticalLayout_3.addWidget(self.table_transactions)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Expense tracker"))
        self.label_current_balance.setText(_translate("MainWindow", "Current Balance"))
        self.label_balance.setText(_translate("MainWindow", "$1200"))
        self.label_income.setText(_translate("MainWindow", "Income"))
        self.income_balance.setText(_translate("MainWindow", "$1200"))
        self.label_outcome.setText(_translate("MainWindow", "Outcome"))
        self.outcome_balance.setText(_translate("MainWindow", "$1200"))
        self.label_expense_tracker.setText(_translate("MainWindow", "Expense categories"))
        self.label_groceries.setText(_translate("MainWindow", "Groceries"))
        self.balance_groceries.setText(_translate("MainWindow", "$1000"))
        self.label_entertair.setText(_translate("MainWindow", "Entertair"))
        self.balance_entertair.setText(_translate("MainWindow", "$1000"))
        self.label_auto.setText(_translate("MainWindow", "Auto"))
        self.balance_auto.setText(_translate("MainWindow", "$1000"))
        self.label_other.setText(_translate("MainWindow", "Other"))
        self.balance_other.setText(_translate("MainWindow", "$1000"))
        self.btn_new_transaction.setText(_translate("MainWindow", "New transaction"))
        self.btn_edit_transaction.setText(_translate("MainWindow", "Edit transaction"))
        self.btn_delete_transaction.setText(_translate("MainWindow", "Delete transaction"))
