# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_transaction.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(338, 378)
        Dialog.setStyleSheet("background: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427 rgba(41, 61, 132, 235), stop:0.98 rgba(155, 79, 165, 255), stop:1 rgba(155, 79, 165, 255));\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(320, 360))
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"boreder: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_new_transaction = QtWidgets.QLabel(self.frame)
        self.label_new_transaction.setStyleSheet("color: white;\n"
"font-size: 18pt;\n"
"background-color: none;\n"
"border: none;\n"
"margin-bottom: 5px;\n"
"font-weight: 600;")
        self.label_new_transaction.setAlignment(QtCore.Qt.AlignCenter)
        self.label_new_transaction.setObjectName("label_new_transaction")
        self.verticalLayout.addWidget(self.label_new_transaction)
        self.cb_category = QtWidgets.QComboBox(self.frame)
        self.cb_category.setStyleSheet("QComboBox {\n"
"font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px;\n"
"}\n"
"\n"
"QComboBox:item {\n"
"color: black;\n"
"}")
        self.cb_category.setCurrentText("Choose category")
        self.cb_category.setMinimumContentsLength(0)
        self.cb_category.setDuplicatesEnabled(False)
        self.cb_category.setObjectName("cb_category")
        self.cb_category.addItem("")
        self.cb_category.addItem("")
        self.cb_category.addItem("")
        self.cb_category.addItem("")
        self.cb_category.addItem("")
        self.cb_category.addItem("")
        self.verticalLayout.addWidget(self.cb_category)
        self.data = QtWidgets.QDateEdit(self.frame)
        self.data.setStyleSheet("color: white;\n"
"font-size: 16pt;\n"
"padding-left: 10px;")
        self.data.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.data.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.data.setObjectName("data")
        self.verticalLayout.addWidget(self.data)
        self.line_description = QtWidgets.QLineEdit(self.frame)
        self.line_description.setStyleSheet("color: white;\n"
"font-size: 16pt;\n"
"padding-left: 10px;")
        self.line_description.setObjectName("line_description")
        self.verticalLayout.addWidget(self.line_description)
        self.line_balance = QtWidgets.QLineEdit(self.frame)
        self.line_balance.setStyleSheet("color: white;\n"
"font-size: 16pt;\n"
"padding-left: 10px;")
        self.line_balance.setObjectName("line_balance")
        self.verticalLayout.addWidget(self.line_balance)
        self.cb_count = QtWidgets.QComboBox(self.frame)
        self.cb_count.setStyleSheet("color: white;\n"
"font-size: 16pt;\n"
"padding-left: 10px;")
        self.cb_count.setObjectName("cb_count")
        self.cb_count.addItem("")
        self.cb_count.addItem("")
        self.verticalLayout.addWidget(self.cb_count)
        self.btn_new_transaction = QtWidgets.QPushButton(self.frame)
        self.btn_new_transaction.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 255, 255, 30);\n"
"color: white;\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"width: 230px;\n"
"height: 50px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/add_box_white_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new_transaction.setIcon(icon)
        self.btn_new_transaction.setIconSize(QtCore.QSize(24, 24))
        self.btn_new_transaction.setObjectName("btn_new_transaction")
        self.verticalLayout.addWidget(self.btn_new_transaction)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Dialog)
        self.cb_category.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_new_transaction.setText(_translate("Dialog", "New Transaction"))
        self.cb_category.setItemText(0, _translate("Dialog", "Choose category"))
        self.cb_category.setItemText(1, _translate("Dialog", "Groceries"))
        self.cb_category.setItemText(2, _translate("Dialog", "Entertainment"))
        self.cb_category.setItemText(3, _translate("Dialog", "Auto"))
        self.cb_category.setItemText(4, _translate("Dialog", "Work"))
        self.cb_category.setItemText(5, _translate("Dialog", "Other"))
        self.line_description.setPlaceholderText(_translate("Dialog", "Description"))
        self.line_balance.setPlaceholderText(_translate("Dialog", "Balance"))
        self.cb_count.setItemText(0, _translate("Dialog", "Income"))
        self.cb_count.setItemText(1, _translate("Dialog", "Outcome"))
        self.btn_new_transaction.setText(_translate("Dialog", "Save new transacton"))
